name = "novogen-brasil"
compatibility_date = "2026-08-05"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "novogen-brasil-db"
database_id = "SUBSTITUA_PELO_DATABASE_ID_DO_D1"
